#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.21
#  in conjunction with Tcl version 8.6
#    May 20, 2019 04:54:38 PM IST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import giencode_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = IMAGE_ENCODE (root)
    giencode_support.init(root, top)
    root.mainloop()

w = None
def create_IMAGE_ENCODE(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = IMAGE_ENCODE (w)
    giencode_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_IMAGE_ENCODE():
    global w
    w.destroy()
    w = None

class IMAGE_ENCODE:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font10 = "-family {Segoe UI} -size 24 -weight bold -underline "  \
            "1 -overstrike 1"
        font13 = "-family {Segoe UI} -size 10 -weight bold"

        top.geometry("600x450+353+150")
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.05, rely=0.067, height=51, width=534)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font10)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''IMAGE STG ENCODER''')
        self.Label1.configure(width=534)

        self.sourcefilebutton = tk.Text(top)
        self.sourcefilebutton.place(relx=0.5, rely=0.4, relheight=0.067
                , relwidth=0.283)
        self.sourcefilebutton.configure(background="white")
        self.sourcefilebutton.configure(font="TkTextFont")
        self.sourcefilebutton.configure(foreground="black")
        self.sourcefilebutton.configure(highlightbackground="#d9d9d9")
        self.sourcefilebutton.configure(highlightcolor="black")
        self.sourcefilebutton.configure(insertbackground="black")
        self.sourcefilebutton.configure(selectbackground="#c4c4c4")
        self.sourcefilebutton.configure(selectforeground="black")
        self.sourcefilebutton.configure(width=10)
        self.sourcefilebutton.configure(wrap='word')

        self.filenamebutton = tk.Text(top)
        self.filenamebutton.place(relx=0.5, rely=0.489, relheight=0.067
                , relwidth=0.283)
        self.filenamebutton.configure(background="white")
        self.filenamebutton.configure(font="TkTextFont")
        self.filenamebutton.configure(foreground="black")
        self.filenamebutton.configure(highlightbackground="#d9d9d9")
        self.filenamebutton.configure(highlightcolor="black")
        self.filenamebutton.configure(insertbackground="black")
        self.filenamebutton.configure(selectbackground="#c4c4c4")
        self.filenamebutton.configure(selectforeground="black")
        self.filenamebutton.configure(width=10)
        self.filenamebutton.configure(wrap='word')

        self.newfilebutton = tk.Text(top)
        self.newfilebutton.place(relx=0.5, rely=0.578, relheight=0.067
                , relwidth=0.283)
        self.newfilebutton.configure(background="white")
        self.newfilebutton.configure(font="TkTextFont")
        self.newfilebutton.configure(foreground="black")
        self.newfilebutton.configure(highlightbackground="#d9d9d9")
        self.newfilebutton.configure(highlightcolor="black")
        self.newfilebutton.configure(insertbackground="black")
        self.newfilebutton.configure(selectbackground="#c4c4c4")
        self.newfilebutton.configure(selectforeground="black")
        self.newfilebutton.configure(width=10)
        self.newfilebutton.configure(wrap='word')

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.183, rely=0.422, height=21, width=164)
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font13)
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''SOURCE FILE(.Extension)''')
        self.Label2.configure(width=164)

        self.Label2_1 = tk.Label(top)
        self.Label2_1.place(relx=0.217, rely=0.6, height=21, width=144)
        self.Label2_1.configure(activebackground="#f9f9f9")
        self.Label2_1.configure(activeforeground="black")
        self.Label2_1.configure(background="#d9d9d9")
        self.Label2_1.configure(disabledforeground="#a3a3a3")
        self.Label2_1.configure(font=font13)
        self.Label2_1.configure(foreground="#000000")
        self.Label2_1.configure(highlightbackground="#d9d9d9")
        self.Label2_1.configure(highlightcolor="black")
        self.Label2_1.configure(text='''NEW FILE(.Extension)''')

        self.Label2_2 = tk.Label(top)
        self.Label2_2.place(relx=0.217, rely=0.511, height=21, width=144)
        self.Label2_2.configure(activebackground="#f9f9f9")
        self.Label2_2.configure(activeforeground="black")
        self.Label2_2.configure(background="#d9d9d9")
        self.Label2_2.configure(disabledforeground="#a3a3a3")
        self.Label2_2.configure(font=font13)
        self.Label2_2.configure(foreground="#000000")
        self.Label2_2.configure(highlightbackground="#d9d9d9")
        self.Label2_2.configure(highlightcolor="black")
        self.Label2_2.configure(text='''DATA FILE(.Extension)''')

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.467, rely=0.733, height=24, width=60)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''INITIATE''')

        self.Label3 = tk.Label(top)
        self.Label3.place(relx=0.35, rely=0.844, height=41, width=194)
        self.Label3.configure(background="#2ad80f")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(text='''0%''')
        self.Label3.configure(width=194)

if __name__ == '__main__':
    vp_start_gui()





