#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.21
#  in conjunction with Tcl version 8.6
#    May 23, 2019 10:32:32 AM IST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import gsencode_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    gsencode_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    gsencode_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font9 = "-family {Segoe UI} -size 24 -weight bold -underline 1"  \
            " -overstrike 1"

        top.geometry("600x450+341+154")
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")

        self.SOUND_STG_ENCODE = tk.Label(top)
        self.SOUND_STG_ENCODE.place(relx=0.25, rely=0.044, height=51, width=325)
        self.SOUND_STG_ENCODE.configure(background="#d9d9d9")
        self.SOUND_STG_ENCODE.configure(disabledforeground="#a3a3a3")
        self.SOUND_STG_ENCODE.configure(font=font9)
        self.SOUND_STG_ENCODE.configure(foreground="#000000")
        self.SOUND_STG_ENCODE.configure(text='''SOUND STG ENCODE''')

        self.sourcetext = tk.Text(top)
        self.sourcetext.place(relx=0.55, rely=0.422, relheight=0.067
                , relwidth=0.283)
        self.sourcetext.configure(background="white")
        self.sourcetext.configure(font="TkTextFont")
        self.sourcetext.configure(foreground="black")
        self.sourcetext.configure(highlightbackground="#d9d9d9")
        self.sourcetext.configure(highlightcolor="black")
        self.sourcetext.configure(insertbackground="black")
        self.sourcetext.configure(selectbackground="#c4c4c4")
        self.sourcetext.configure(selectforeground="black")
        self.sourcetext.configure(width=10)
        self.sourcetext.configure(wrap='word')

        self.datatext = tk.Text(top)
        self.datatext.place(relx=0.55, rely=0.511, relheight=0.067
                , relwidth=0.283)
        self.datatext.configure(background="white")
        self.datatext.configure(font="TkTextFont")
        self.datatext.configure(foreground="black")
        self.datatext.configure(highlightbackground="#d9d9d9")
        self.datatext.configure(highlightcolor="black")
        self.datatext.configure(insertbackground="black")
        self.datatext.configure(selectbackground="#c4c4c4")
        self.datatext.configure(selectforeground="black")
        self.datatext.configure(width=10)
        self.datatext.configure(wrap='word')

        self.outputtext = tk.Text(top)
        self.outputtext.place(relx=0.55, rely=0.6, relheight=0.067
                , relwidth=0.283)
        self.outputtext.configure(background="white")
        self.outputtext.configure(font="TkTextFont")
        self.outputtext.configure(foreground="black")
        self.outputtext.configure(highlightbackground="#d9d9d9")
        self.outputtext.configure(highlightcolor="black")
        self.outputtext.configure(insertbackground="black")
        self.outputtext.configure(selectbackground="#c4c4c4")
        self.outputtext.configure(selectforeground="black")
        self.outputtext.configure(width=10)
        self.outputtext.configure(wrap='word')

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.3, rely=0.422, height=21, width=134)
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''SOURCE FILE(.Extention)''')

        self.Label3 = tk.Label(top)
        self.Label3.place(relx=0.317, rely=0.533, height=21, width=121)
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(text='''DATA FILE(.Extention)''')

        self.Label4 = tk.Label(top)
        self.Label4.place(relx=0.167, rely=0.622, height=21, width=216)
        self.Label4.configure(background="#d9d9d9")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(text='''NAME OUTPUT SOUND FILE(.Extention)''')

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.467, rely=0.733, height=25, width=55)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''INITIATE''')

        self.Label5 = tk.Label(top)
        self.Label5.place(relx=0.35, rely=0.844, height=41, width=202)
        self.Label5.configure(background="#0fd837")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(text='''0%''')
        self.Label5.configure(width=202)

if __name__ == '__main__':
    vp_start_gui()





